### ISSUE TITLE
Date of administration data

### ISSUE THREAD

**Issue by Tugzrida** [jxeeno/aust-govt-covid19-vaccine-pdf#16]
In the readme, you mention that "Department of Health has also begun reporting doses on the date of administration. This data is not available in this repository yet."

Would you be able to point me to where DOH reports doses by administration date? I've spent quite a while scouring their website but can't seem to find it 😅

**Comment by jxeeno** [comment]
Hey, it's in the jurisdiction slide deck:

![image](https://user-images.githubusercontent.com/23213119/132446149-5bdf8108-2e8e-4bc8-96ea-e1ed5e53bc7f.png)

It'll only give you the last 7 days of doses by date of administration.

**Comment by Tugzrida** [comment]
Ah, I'd found that but assumed it was just date of reporting data again as from a brief look it seemed to be the same numbers.

Doing a few more comparisons now, state clinics seem to match exactly the existing data in all.json, whereas primary and aged care have differences.

A little disappointing as when I read your note, I was hoping I could find some data that wasn't affected by the recent state clinic reporting glitches 😂
