### ISSUE TITLE
Erroneous data point

### ISSUE THREAD

**Issue by aaronw22** [jxeeno/aust-govt-covid19-vaccine-pdf#17]
Hi Ken,

I think there is an erroneous data point in the air_residence.csv file for WA 16+ in the AIR_RESIDENCE_SECOND_DOSE_COUNT column. The value in that cell jumps from 503484 the previous day to 1475180, before dropping to 530080. Not sure if there is an error on the Commonwealth PDF or the scraper just went wild for a moment.

Also, thanks making the scraped data publicly available. Legend!

**Comment by jxeeno** [comment]
Hi @aaronw22 

Thanks for flagging.  Yep, looks like an issue in the PDF - looks like they forgot to copy&paste the VIC values in the WA slide: https://www.health.gov.au/sites/default/files/documents/2021/08/covid-19-vaccine-rollout-update-jurisdictional-breakdown-18-august-2021.pdf

Should be corrected now :)

Cheers,
Ken
