### ISSUE TITLE
Dealing with impending change to AIR age groups reported

### ISSUE THREAD

**Issue by chrisjbillington** [jxeeno/aust-govt-covid19-vaccine-pdf#2]
Hi Ken,

Thanks for this excellent data service!

With Pfizer now approved for ages 12+ in Australia, the AIR data in the PDFs is presumably going to change the age groups for which stats are reported (maybe this is why data is late today). I was wondering how you're planning to incorporate this into your datasets and thought I'd suggest one option.

The gov will presumably no longer report data for the 16-19 age group, instead adding a 12 - 14 and a 15 - 19 group. So for dates after the change, you might simply include all the data for these new age groups as normal, and the data for the 16 - 19 group will be missing or NaN.

For dates before the change you can keep all the data that's there, but might consider adding data for the 15 - 19 age group columns instead of having them be empty. These would have dose numbers that are just a copy of what's there already for the 16 - 19 group, and percentages calculated from those dose numbers using the same population data the government uses when reporting these statistics. They use data from [ABS Estimated Resident Population, June 2020](https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/jun-2020), which, to save you the trouble has:
```
M 15 - 19: 767801
F 15 - 19: 725052
```

You could also fill the doses and percentages for the 12 - 15 age group with zeros, for dates prior to the change.

Does that make sense?

If you don't do this and just have empty data for the new age groups for old dates, that's fine since I can just do the above conversion in my own code!

Thanks again.

**Comment by jxeeno** [comment]
Hey @chrisjbillington

Thanks for flagging! Was just thinking about this earlier today...

The PDF just got published but it was circulated to media earlier today but for some reason it took them till now to publish 🤷   The age groups remain unchanged for today's presentation.

I think the approach you suggested would work.  We'll confirm when the PDFs update and the new age buckets are confirmed, but the intention would be to:

* retain the 16-19 fields for historical purposes and provide empty fields moving forward
* create new fields for the new buckets
* where possible, backfill new fields with existing data and recalculate percentages

Will check with a few known downstream consumers as well and see what they think.

**Comment by jxeeno** [comment]
Department of Health is now publishing dose data for 12-15 year olds. This data is available in air.csv as:

* AIR_12_15_<FIRST|SECOND>_DOSE_<COUNT|PCT>
* AIR_<STATE>_12_15_<FIRST|SECOND>_DOSE_<COUNT|PCT>

I understand these doses aren't counted in some of the totals. Will be working to confirm which are included and which are excluded and update here in due course.

**Comment by chrisjbillington** [comment]
[rad!](https://chrisbillington.net/coverage_by_agegroup.svg)

Thanks for your tireless work, Ken!

**Comment by jxeeno** [comment]
Closing this issue now!
