### ISSUE TITLE
Updated PDF layout expected 16 Aug

### ISSUE THREAD

**Issue by jxeeno** [jxeeno/aust-govt-covid19-vaccine-pdf#7]
Heads up, we're expecting a new layout for the daily vaccination stats PDF slide deck today.

I've paused the auto scraper for now so it doesn't accidentally send through rouge data. I will be working on updating the scraper once the new PDF is published.

**Comment by jxeeno** [comment]
Existing AIR datasets are now up-to-date:

* air.csv / json
* air_residence.csv / json
* air_sa4.csv / json

Still working out what to do with all.csv moving forward.

**Comment by Tugzrida** [comment]
I've noticed that the latest entry in air.json is marked as not validated. Is that an actual validation error or did the format change also break the validator?

Thanks for your efforts! :)

**Comment by jxeeno** [comment]
> I've noticed that the latest entry in air.json is marked as not validated. Is that an actual validation error or did the format change also break the validator?
> 
> Thanks for your efforts! :)

Hey! Unfortunately, the validation flag is actually based on all data including the missing data in `all.csv`.  I'll be filling in the missing data shortly so it should mean the validation flag will be fixed soon

**Comment by Tugzrida** [comment]
Wonderful thank you!

**Comment by jxeeno** [comment]
all.csv/json has also been manually updated.  I'll add a data note about the change in the way data is reported soon.

Outstanding issues are:

- [ ] Investigate if it's possible to exclude text hidden underneath the presentation when parsing the PDF
- [ ] Update pipeline to handle new 
- [ ] Add data note about removal of self-reporting

**Comment by Tugzrida** [comment]
Is there somewhere I'm missing where state totals and daily increases are recorded? I was getting it by adding primary care, aged care and state clinics, but primary care isn't broken down anymore. The second slide does now have totals/increases and then there's the "Commonwealth" figures on the 4th.

It could very well be there but I need some sleep before trying to figure out any more 😅

**Comment by jxeeno** [comment]
I pushed up some updated data a few mins ago with the primary care data.  It's not separately published anymore, but it can be derived by subtracting total commonwealth doses by the aged care/disability doses.

**Comment by Tugzrida** [comment]
Thank you so much Ken!

I guess it would be nice to have the state totals, but for consistency with the previous data, I think what you've got now is good. Running it through some graphs I've been using, it's fairly consistent with previous days, apart from a step increase in the ACT primary care total and some of the daily changes being a bit low, as expected with the change in data source.

I'll keep my updaters running manually for the next few days and let you know if I notice any issues.
