### ISSUE TITLE
Clarity in Age Range in AIR Residence data

### ISSUE THREAD

**Issue by willy-cs** [jxeeno/aust-govt-covid19-vaccine-pdf#9]
Hi Kenneth,

First, thanks for all your effort in providing excellent data and public services during this tough times.

I had a poke around at the AIR residence data (https://vaccinedata.covid19nearme.com.au/data/air_residence.csv), and noticed a minor issue that might cause data misinterpretation.

I note that each state have two types of bracket groups, e.g. the 5 year interval groups, and the special 0-999, 50-999, 70-999, and 95-999 groups. 

My first impression reading the numbers for AGE_LOWER 0 and AGE_UPPER 999 rows is that these are the entire population of each state across all ages.  For example in VIC, the 'ABS_ERP_JUN_2020_POP' column is 5407574. However, a quick Wikipedia search and ABS data ( https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/dec-2020/31010do001_202012.xls) shows that the total population for VIC is 6.6 million. 

After a few more checks by summing up the population for the 5 year interval groups, I think the figures you use for AGE_LOWER 0 and AGE_UPPER 999 are actually the figures for population over 16. Therefore, personally, I think the rows should read as AGE_LOWER 16 and AGE_UPPER 999 to clear up the confusion.

Apologies if you might have mentioned this somewhere or if that's what you've intended in the first place.

Thanks,
Willy.

**Comment by jxeeno** [comment]
Hi Willy,

I believe you're right.  The population figures comes from this slide (top right corner) which uses the header "Total".  I must have misinterpreted this as meaning whole population.

![image](https://user-images.githubusercontent.com/23213119/130313293-352a85e4-4dc1-4ab0-8656-0b1465bbd350.png)

I'll add an update correct this.  We may need to calculate our own values for 0-999 for backwards compatability.

Cheers,
Ken

**Comment by willy-cs** [comment]
Thanks for the reply.

With regards to 0-999, it might be possible to use the ABS data directly in your code or pipeline. The total population figure is constant (for this data and purpose anyway).

![image](https://user-images.githubusercontent.com/65746126/130313793-6d69d769-0d63-48bf-b594-babc73101213.png)


Keep up the good work.

**Comment by jxeeno** [comment]
Thanks Willy, I've corrected the ageLower field to say 16 now.  Should be good now, but let me know if something's off.

I'm not sure if we need to regenerate for 0+ at this stage, but if any consumers want it, let me know and I can add it in.
